### ISSUE TITLE
no longer install latest snap - depends on core22

### ISSUE THREAD

**Issue by danie-dejager** [maxiberta/htop-snap#17]
I can no longer install the latest snap for htop, I get this:
```
→ snap install htop
error: cannot perform the following tasks:
- Ensure prerequisites for "htop" are available (cannot install snap base "core22": snap "core22" assumes unsupported features: snapd2.55.5 (try to refresh snapd))
```
```
→ snap list
Name                    Version   Rev    Tracking       Publisher     Notes
core20                  20220527  1518   latest/stable  canonical✓    base
snapd                   2.56      16010  latest/stable  canonical✓    snapd
```
The host is running Rocky Linux 8.6. The RPM installed is snapd-2.55.3-1.el8.x86_64.

**Comment by maxiberta** [comment]
Hm, that looks like an issue with snapd integration in your system, unrelated to the `htop` snap itself (`htop` was recently ported to "core22" base, which needs to be installed first).

That said, maybe try to restart the snapd service, or just reboot if you haven't already. What's the output of `snap version`? Also, I wonder what'd happen if you attempt to install `core22` manually - I'd expect it'll fail?

Otherwise, the [snapcraft forum's "snapd" category](https://forum.snapcraft.io/c/snapd/5) is probably the best place to ask.

**Comment by danie-dejager** [comment]
@maxiberta Here is the output:
```
→ snap version
snap    2.55.3-1.el8
snapd   2.55.3-1.el8
series  16
rocky   8.6
kernel  4.18.0-372.9.1.el8.x86_64
```
I'll post on the forum and update here if I learn anything new.

**Comment by danie-dejager** [comment]
https://forum.snapcraft.io/t/no-longer-install-latest-htop-snap-depends-on-core22/30609
